name: CI Build

env:
  REPOSITORY: glasswallsolutions
  IMAGE: reference-ncfs
  TAG: develop

on:
  push:
    branches: [develop]
    
jobs:
  build-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        username: icapserviceaccount
        password: ${{ secrets.ICAPDOCKERSECRET }}
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-${GITHUB_SHA::7} -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-latest .
        docker push ${{ env.REPOSITORY }}/${{ env.IMAGE }}
    - name: Install yq - portable yaml processor
      run: |
        sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq

  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master
      - name: Merge to main branch 🔃
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: main
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN_GITHUB}}  
